# Introduction to time series
## What is time?

One definition of time as we percieve it is the observations of **events** as features of those events change. Think of a movie reel and how for evey frame a diffrecnt set of actions occur. These 'actions' can be quantified as features in any dataset based on the time in which they occur. What time series really seeks to point out is **what events occured at this point in time"**. This is incredibly powerful as time series is the backbone of nearly every industry. Here are some examples in which time series can be used:
> - Looking at your github data to see which days you do what type of programming, for how long, ect
> - In Fintech it's uses can be seen in studying past trends in crypto currency
> - In the banking industry for fraud dectection and stocks and bonds trading
> - In scientific analysis to study the effects of inputs in eperiements over time
> - Many more...

## Discussion:
### Discuss how you conceptualize time asn well as give three examples of when measuring time in your everyday life could be interesting

The libray that we will use for retureiving financial, economic and sociology data is the python api for Quandl.
Install this via anaconda with the following command. conda install -c anaconda quandl (you may have to use sudo)

In [21]:
# quandl for financial data
import quandl
# pandas for data manipulation
import pandas as pd

# Use your API Key

quandl.ApiConfig.api_key = ''


# Retrieve TSLA data from Quandl
tesla = quandl.get('WIKI/TSLA')

In [20]:
tesla.head(5)

,Open,High,Low,Close,Volume,Ex-Dividend,Split Ratio,Adj. Open,Adj. High,Adj. Low,Adj. Close,Adj. Volume
Date,,,,,,,,,,,,
2010-06-29,19.00,25.0000,17.54,23.89,18766300.0,0.0,1.0,19.00,25.0000,17.54,23.89,18766300.0
2010-06-30,25.79,30.4192,23.30,23.83,17187100.0,0.0,1.0,25.79,30.4192,23.30,23.83,17187100.0
2010-07-01,25.00,25.9200,20.27,21.96,8218800.0,0.0,1.0,25.00,25.9200,20.27,21.96,8218800.0
2010-07-02,23.00,23.1000,18.71,19.20,5139800.0,0.0,1.0,23.00,23.1000,18.71,19.20,5139800.0
2010-07-06,20.00,20.0000,15.83,16.11,6866900.0,0.0,1.0,20.00,20.0000,15.83,16.11,6866900.0